Renamed repository to sicc

diff --git a/ir/Dockerfile b/ir/Dockerfile
--- a/ir/Dockerfile
+++ b/ir/Dockerfile
@@ -25,15 +25,15 @@ ENV PATH="/usr/lib/llvm-17/bin:$PATH"
 RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
 ENV PATH="/root/.cargo/bin:${PATH}"
 
-WORKDIR /usr/starter_code
+WORKDIR /usr/sicc
 
-VOLUME ["/usr/starter_code/ir", "/usr/starter_code/common", "/usr/starter_code/integration"]
+VOLUME ["/usr/sicc/ir", "/usr/sicc/common", "/usr/sicc/integration"]
 
-CMD if [ "$(ls -A /usr/starter_code/ir)" ]; then \
+CMD if [ "$(ls -A /usr/sicc/ir)" ]; then \
         /bin/bash; \
     else \
-        echo "Error: /usr/starter_code/ir does not exist or is empty" && exit 1; \
+        echo "Error: /usr/sicc/ir does not exist or is empty" && exit 1; \
     fi
 
 # To build this, use: `docker build -t ir-env .`
-# To run this, use: `docker run -it --rm -v $(pwd):/usr/starter_code/ir -v $(pwd)/../common:/usr/starter_code/common -v $(pwd)/../integration:/usr/starter_code/integration ir-env`
+# To run this, use: `docker run -it --rm -v $(pwd):/usr/sicc/ir -v $(pwd)/../common:/usr/sicc/common -v $(pwd)/../integration:/usr/sicc/integration ir-env`
diff --git a/lexer/Dockerfile b/lexer/Dockerfile
--- a/lexer/Dockerfile
+++ b/lexer/Dockerfile
@@ -13,15 +13,15 @@ RUN apt-get update && apt-get install -y \
 RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
 ENV PATH="/root/.cargo/bin:${PATH}"
 
-WORKDIR /usr/starter_code
+WORKDIR /usr/sicc
 
-VOLUME ["/usr/starter_code/lexer", "/user/starter_code/common"]
+VOLUME ["/usr/sicc/lexer", "/user/sicc/common"]
 
-CMD if [ "$(ls -A /usr/starter_code/lexer)" ]; then \
+CMD if [ "$(ls -A /usr/sicc/lexer)" ]; then \
         /bin/bash; \
     else \
-        echo "Error: /usr/starter_code/lexer does not exist or is empty" && exit 1; \
+        echo "Error: /usr/sicc/lexer does not exist or is empty" && exit 1; \
     fi
 
 # To build this Dockerfile, use: `docker build -t lexer-env .`
-# To run this, use: `docker run -it --rm -v $(pwd):/usr/starter_code/lexer -v $(pwd)/../common:/usr/starter_code/common lexer-env`
+# To run this, use: `docker run -it --rm -v $(pwd):/usr/sicc/lexer -v $(pwd)/../common:/usr/sicc/common lexer-env`
diff --git a/parser/Dockerfile b/parser/Dockerfile
--- a/parser/Dockerfile
+++ b/parser/Dockerfile
@@ -13,15 +13,15 @@ RUN apt-get update && apt-get install -y \
 RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
 ENV PATH="/root/.cargo/bin:${PATH}"
 
-WORKDIR /usr/starter_code
+WORKDIR /usr/sicc
 
-VOLUME ["/usr/starter_code/parser", "/usr/starter_code/lexer", "/user/starter_code/common"]
+VOLUME ["/usr/sicc/parser", "/usr/sicc/lexer", "/user/sicc/common"]
 
-CMD if [ "$(ls -A /usr/starter_code/parser)" ]; then \
+CMD if [ "$(ls -A /usr/sicc/parser)" ]; then \
         /bin/bash; \
     else \
-        echo "Error: /usr/starter_code/parser does not exist or is empty" && exit 1; \
+        echo "Error: /usr/sicc/parser does not exist or is empty" && exit 1; \
     fi
 
 # To build this Dockerfile, use: `docker build -t parser-env .`
-# To run this, use: `docker run -it --rm -v $(pwd):/usr/starter_code/parser -v $(pwd)/../common:/usr/starter_code/common -v $(pwd)/../lexer:/usr/starter_code/lexer parser-env`
+# To run this, use: `docker run -it --rm -v $(pwd):/usr/sicc/parser -v $(pwd)/../common:/usr/sicc/common -v $(pwd)/../lexer:/usr/sicc/lexer parser-env`
diff --git a/sts/Dockerfile b/sts/Dockerfile
--- a/sts/Dockerfile
+++ b/sts/Dockerfile
@@ -13,15 +13,15 @@ RUN apt-get update && apt-get install -y \
 RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
 ENV PATH="/root/.cargo/bin:${PATH}"
 
-WORKDIR /usr/starter_code
+WORKDIR /usr/sicc
 
-VOLUME ["/usr/starter_code/sts", "/user/starter_code/common"]
+VOLUME ["/usr/sicc/sts", "/user/sicc/common"]
 
-CMD if [ "$(ls -A /usr/starter_code/sts)" ]; then \
+CMD if [ "$(ls -A /usr/sicc/sts)" ]; then \
         /bin/bash; \
     else \
-        echo "Error: /usr/starter_code/sts does not exist or is empty" && exit 1; \
+        echo "Error: /usr/sicc/sts does not exist or is empty" && exit 1; \
     fi
 
 # To build this Dockerfile, use: `docker build -t sts-env .`
-# To run this, use: `docker run -it --rm -v $(pwd):/usr/starter_code/sts -v $(pwd)/../common:/usr/starter_code/common sts-env`
+# To run this, use: `docker run -it --rm -v $(pwd):/usr/sicc/sts -v $(pwd)/../common:/usr/sicc/common sts-env`
